sudo: required
dist: trusty
language: rust

env:
  ZOLA=${TRAVIS_BUILD_DIR}/zola
  MDBOOK=${TRAVIS_BUILD_DIR}/mdbook

before_install:
  - bash install_zola.sh
  - bash install_mdbook.sh

## All scripts are run above...
script: make site
after_success: make deploy
