sudo: required
dist: trusty
language: rust

env:
  ZOLA=${TRAVIS_BUILD_DIR}/zola
  MDBOOK=${TRAVIS_BUILD_DIR}/mdbook
  CURRENT_BRANCH=${TRAVIS_BRANCH}
  SITE_TARGET_DIR=${TRAVIS_BUILD_DIR}/target/site

before_install:
  - bash install_zola.sh
  - bash install_mdbook.sh
  - bash install_openssl_deb.sh

## All scripts are run above...
script: make site

# using pages deploy
#after_success: make deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_TOKEN
  keep_history: true
  local_dir: $SITE_TARGET_DIR
  target_branch: gh-pages
  verbose: true
  on:
    branch: master
