sudo: required
dist: trusty
language: rust

env:
  ZOLA=./zola
  MDBOOK=./mdbook

before_install:
  - bash install_zola.sh
  - bash install_mdbook.sh

## All scripts are run above...
script: make site

after_success: make deploy
